import { Boxes, Gauge, TrendingDown } from 'lucide-react'
import AITag from './AITag'

const QA = [
  {
    icon: <Gauge size={13} />,
    q: 'How does the system maximise capacity vs the demand forecast?',
    a: 'The demand sensing engine reads POS sell-through, promo calendars and festival signals to produce sensed demand per store × SKU. Every replenishment quantity is clamped to the store\'s open-to-ship headroom, so on-hand never exceeds max capacity.',
  },
  {
    icon: <Boxes size={13} />,
    q: 'What is the ideal inventory for each store?',
    a: 'Ideal on-hand = safety stock + sensed demand over lead time. Safety stock is sized to hold a 98% service level against demand variability; the optimiser orders only the net requirement that closes the gap.',
  },
  {
    icon: <TrendingDown size={13} />,
    q: 'How is transportation cost reduced?',
    a: 'Store orders are consolidated onto shared DC lanes. FTL loads at 85%+ truck fill avoid the LTL premium; FTL (consol.) pairs two stores on one truck (~22% saving); milk-run routing serves small top-ups on a single vehicle.',
  },
]

export default function AIRationalePanel() {
  return (
    <section className="rounded-lg border border-dashed border-purple/45 bg-purple-light/20 h-full flex flex-col">
      <div className="flex items-center gap-2 px-4 pt-3.5 pb-2.5 border-b border-purple/15">
        <AITag label="AI-optimized" />
        <span className="text-[11px] text-ink4">Plan rationale</span>
      </div>
      <div className="p-4 space-y-4 flex-1">
        {QA.map((item, i) => (
          <div key={i} className="flex gap-2.5">
            <div className="w-6 h-6 rounded-md bg-purple-light text-purple flex items-center justify-center flex-shrink-0 mt-0.5">
              {item.icon}
            </div>
            <div className="min-w-0">
              <div className="text-[12px] font-semibold text-ink mb-1 leading-snug">{item.q}</div>
              <p className="text-[11.5px] text-ink3 leading-relaxed">{item.a}</p>
            </div>
          </div>
        ))}
      </div>
      <div className="px-4 py-2.5 border-t border-purple/15 text-[10.5px] text-ink4">
        Generated by the AI replenishment optimiser · objective: minimise network transportation cost at 98% service level
      </div>
    </section>
  )
}
